### ISSUE TITLE
Section structure not correct

### ISSUE THREAD

**Issue by drgrigg** [michael-77/thomas-hardy_tess-of-the-d-urbervilles#1]
You've done a great job with the ToC with the proper nesting. But the chapter files within each part need to reflect the correct sectioning, and which part they are in. The chapter naming should also reflect this structure eg chapter-1-1.xhtml... chapter-2-1.xhtml etc. 

t's easier to illustrate what I mean than explain in words. Your chapter 12.xhtml, for example should be named chapter-2-1.xhtml and begin like this:

`	<body epub:type="bodymatter z3998:fiction">`
`		<section id="part-2" epub:type="z3998:part">`
`			<section id="chapter-2-1" epub:type="chapter">`
`				<h2 epub:type="title z3998:roman">I</h2>`

The end of each file thus has two `</section>` tags:

`			</section>`
`		</section>`
`	</body>`
`</html>`

Have a look at the source code for other SE books with this kind of structure, such as "No Name" or "Omega".

**Comment by drgrigg** [comment]
However, having said all that, I've just looked at the page scans and see that the Roman numerals for chapter numbers continue throughout. So it would be silly to rename the chapter files and not make them match the Roman numerals. Might need to get Alex to adjudicate this one.

**Comment by michael-77** [comment]
Thank goodness for regular expressions :smile:
