### ISSUE TITLE
CSS issues

### ISSUE THREAD

**Issue by drgrigg** [michael-77/thomas-hardy_tess-of-the-d-urbervilles#2]
In local.css, there's a lot of very complex styling for the epigraph. I don't understand why this is necessary, and it appears to run against the SE standards. 

It's also commented as "All epigraphs and dedication", but there seems to be only a single epigraph and no dedication. Has the CSS been copied from some other work?

**Comment by michael-77** [comment]
The epigraph code is copied from https://standardebooks.org/contribute/semantics#epigraphs
I will remove the comment about dedications in the css file as you correctly observed that the comment was copied and pasted from another production.

**Comment by drgrigg** [comment]
My mistake! I hadn't seen all that material about epigraphs in the semantics manual. I think Alex must have added it recently.
